### ISSUE TITLE
Unable to find enocder and decoder for wav

### ISSUE THREAD

**Issue by kshitij12345** [devsnd/python-audiotranscode#6]
It cant find enocder and decoder for wav while it can find decoder for mp3 and ogg which i installed later

**Comment by devsnd** [comment]
The encoder and decoder for wav is actually a no-op. All other encoders are forced to write WAV files, so they can exchange channels, bitrate and samplerate using wavs RIFF headers.

Basically, the wav encoder should be available on any unix system, since this is using the `cat` command. Are you using a unix system like linux or OSX?

**Comment by kshitij12345** [comment]
Thank you very much for your instant reply.. i m on windows.. though now
its working . Had to find an external codec.. but it works like a charm ..
so thank you very very much.. appreciate it..
